language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: ky1BiAPW4Jg/fA8BMlqpvnmZLeOejleQRb70/zpcfsgbB7E64P8g5wat5kmLBTFQTLEpvWn38D/4L6O3FZdIqbCxk4ZsicD1xWPZbIg3wXSMk7a9grrtio0ijcucJ220h3OviDpiIT/Jd1rsEJ+EXrzVPKVNOsJ1llfjsmLQwS23HXkh2ICC0exKqMgZNqtj/CE0rKVsAuXKRou5DJ5j9YghRDbP57cTMNGBvXX04l/3JDKe9wCHtIjvAp4+UOr27V/bv7pPp9uVTO0JaQQ8hnHCe79Fwc2iChltiEsInEp2RCI3YMn+WmL14b3x/RZ26KB3TG5asVaSNO4gMuTVcpXr5rb7Nwa9+uqloMicJam4wZ7A7+6+TdpN7iKB9HrcRGBjdrqg3R0ASpQ6CcVMbA7KiNAQSHEk1fIbhivY7/BwZuQBUgQK1mO8K8J56+V/vdQabnMNHHhA2zQYanHpKTNxRtX1OTpNhc+wrMLGDanTJnIQyHXQ4ybaugQN4Gm4ZH7ON4jfzdweLAPxY6IUFlg9G/BtaWyxisKQyzyzUcBQTZpjvGesTWfNKQEJD8q3oKneMBGKl7qjhiN3jD3jCT/U6xZ6bCyhS0i4wHkd4Zjmy15g4ckMYQZF4Tui6c1Nh4ihjJMqLq251/5LRxpjdm4fINQYn9nYFXtjohALQvs=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: IAW7hWlYc25cbited/APZ9GDQ3DR3SmB7c8scF/AUHTr/GvaSwl0uOMBgYzIWnh1ZhawZxioVefmOScOlDePQzgmE2QN3/3ZrkUzklo9v6Jv7spiX6pnk3/KSiNvCo2dC7h0G3WCPnLVJZPDpjX7kc3Ooy728H4wlGY4dcBUHMmwYsdEyvV0yBLDLjPO+LEcwEGx7fUcJGb4CKQ/V73bNcFXxBVX2eodrlq/r+h3rgOFhDaq43NASUFUa3KpbksSlg4yUplH0sEBXAdu6bou5tgDOc9jbfQOvEhpfw31lWnQiXkqI+A8ji2wYW+tpyipm03XFkM312K1Hegxvyv1ANzTzUl0u5pqJLEv/2Zk7qPhsO7ETg8hkA/rPjNslMnCXACKQ62s3M5jv4Wr1HEIqtmm/JJPtkgvyaM8A4KlHCEjRKFwpkSTHQkhq25zB+LllwqoRcuN4oqZzBXwSG24cVNFj4l4UOU1KMbN2ykdEWdFLuI0GtT7YLjGmOeXtAK5YPU3tMGSqdeZKhB7o63eRiYvUNAYzGsNhMpiLHFB6iS7zaPawKUIhm6QQ8jLNJorbiMLmRPYPlIzSCuv/oHnVZOZIG5HVpXl9faJ6qX6J+8iV1pvL00Sy0PfOVI+oeGZilIO6BO/D+ZLZYvSYykLJVGfYMOhOLBe/hgQZLvVuMY=
  - secure: V5XY//LNMVibc518wsv7Vd5tY2le/Dv7LRS+KM1hQHDPA6NQUQpJvq4wLatgLcNED6LU11QcxK6eOjmnUWUL2bWO8qhAsF72jn3Q4kQWta3ah0xOaM2XHz1TlxH1MRiXUXyt5PYQ/zI7VhscdlA+lco/OdntrrwUF6JbD+yzCRT1DxvmghSU4OAGVJ2ZUTeIRUUIOA6ojYYnqyB2G1xmoKqkQvisusZy8arW3xbaaAZJjUK3vEBdyd6J41jDqqOwSvQ1w0Koah4Grdvfwl+dkxgZK7E7zuZSlaodtBcXUc0Z3eVLJRf63f0JB5n2EROWqRDh+hLO0WJCn6bCLPxQCmaANDycQSy1qJvxxqrRnyx0QppCPEGAD0G0P1A3wr3YFBcmhvrmeSkY+EPeCYlwzY/95l8ySts3ZJImSlOFBYVNh7SNrj2XIG0r2Ir0Ue7IDH5PjxctWTSk9hpZM5HbwxApP/1XwOQwhBTOcoG8L26vvAhq9Oq9c8mDF0WZUVICoL4JeUCF3RK2WjD53jN7JAjnHMgGiskB485q2vm+zlZE3bPA+2vuJ3GfCBl5VYBbc10aTRQPMedgNgp4kkM9RsvBVM6hmMUUoD33quoIENgd9EJPbQJoqiY6tvTJpaWlANk45+oVqyp/AuMA9rBaCMqjItQ3m5CBZhTQCE5d/X0=
  - secure: Yo5luL1YLfG/A2lUxryJiKklQCixhJwL3uqzjh6s7hS7aU4pHkNe1GYYf0CbG2hD77ensqGEO/9N02sRwnfmJEvzorOg/0wd+IHDOaLa3YUMJw0TX8ocG7KjE5UQIfVLup9UJY1XvtrVWEu4pGcaNOtVO+PhadvgjPjMv+2ghVN+fU4zkRjjKIPyCCB6O47yEfY6P0ZTVgQqSsq8QBEjTlIKYUhT636uN9UgggdXT7EJN+e8sXsfCzURsbbFw9qrjoTyOG9/WtfwBXai8npJzyuJKIbCBwRDtoaw0zIVGEqUY97w0d/5ZKk2YfFgeORgIWYuVxXMfQxRhStz+jVtMapkdlTP13QMimkKgBQCjwUu5IvCUI+QKqd7esVm8AWcUzdWKh3xmN9lH1Kp0Ehp9AjiVrgSy0rkslJrzmuQVjb6D9jzWCiHq2HfpCAAAJFIr0PjluA0SiUmzW3bKwlZBV3QeG17r5a5I+ecgka3AvB9buXqWYDFmSlIq/ctJl9jBe/2YwDv1yIt/U4Nea5sr/LB/VcmKzdwMevcuAXtsqwKTTeg7D5KalHoQoOv9Hye+Ui3k8kPF947Kj+xGMitWBL8Q2RaTcugzIDfgpKUMNw1ei0EIX2HDe/F7vhd0idV3LEx3B7a3f7uu4YGu/fuaUd3L+zQQGkHmFwVao2V+f8=
before_install:
- openssl aes-256-cbc -K $encrypted_1e60cba3372a_key -iv $encrypted_1e60cba3372a_iv
  -in lof-ws-test-5c33f02ea8c8.json.enc -out ${TRAVIS_HOME}/lof-ws-test-5c33f02ea8c8.json -d
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=pub-onlinedogshow-daemon-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export GOOGLE_APPLICATION_CREDENTIALS=${TRAVIS_HOME}/lof-ws-test-5c33f02ea8c8.json
script:
- sh scripts/travis/tag_build.sh
- sh scripts/travis/build_services.sh
- sh scripts/travis/deploy_to_docker_hub.sh
