version: '2'
services:
  pubonlinedogshowdaemon:
    image: anthonydenecheau/pub-onlinedogshow-daemon:${TAG_PUB_ODS_SERVICE}
    container_name: pub-onlinedogshowdaemon
    restart: always    
    ports:
      - "8100:8100"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8100"
      #GOOGLE_PROJECT_ID: "lof-ws-test"
      # not specify on gcp
      GOOGLE_APPLICATION_CREDENTIALS: "/tmp/lof-ws-test-5c33f02ea8c8.json" 
      # set encrypted key on machine
      #ENCRYPT_KEY:         ${ENCRYPT_KEY}
      _JAVA_OPTIONS:       "-Xms256m -Xmx512m"
      JAVA_SECURITY_EGD: "file:/dev/./urandom"
    volumes:
      # mount directory where file has been deployed on local machine
      - /home/userscc:/tmp
    extra_hosts:
       - "lof:10.3.2.80"
volumes:
  tmp:
